### ISSUE TITLE
pull request not cherry picked

### ISSUE THREAD

**Issue by nyotiemon** [dufourgilles/knx-ip#5]
Hi, apologize for opening another issues. But you should notice that #3 is having more than one commit. It was my mistake not knowing how pull-request work and just commit to my repo with intention for my own usage.
Please check your work, 2 commits on Aug 10th (ed7f52d and e359fd8) added `lib` dir, modified `package.json` and whole bunch `index.ts` for default export class naming.

I think you need to be aware of this. Sorry!

**Comment by dufourgilles** [comment]
ok. thanks for info. I didn't pay attention.  Only checked the code change.
Please submit another pull request with only your changes.
